INSERT INTO UF (nome, sigla) VALUES ('Acre', 'AC');
INSERT INTO UF (nome, sigla) VALUES ('Alagoas', 'AL');
INSERT INTO UF (nome, sigla) VALUES ('Amapá', 'AP');
INSERT INTO UF (nome, sigla) VALUES ('Amazonas', 'AM');
INSERT INTO UF (nome, sigla) VALUES ('Bahia', 'BA');
INSERT INTO UF (nome, sigla) VALUES ('Ceará', 'CE');
INSERT INTO UF (nome, sigla) VALUES ('Distrito Federal', 'DF');
INSERT INTO UF (nome, sigla) VALUES ('Espírito Santo', 'ES');
INSERT INTO UF (nome, sigla) VALUES ('Goiás', 'GO');
INSERT INTO UF (nome, sigla) VALUES ('Maranhão', 'MA');
INSERT INTO UF (nome, sigla) VALUES ('Mato Grosso', 'MT');
INSERT INTO UF (nome, sigla) VALUES ('Mato Grosso do Sul', 'MS');
INSERT INTO UF (nome, sigla) VALUES ('Minas Gerais', 'MG');
INSERT INTO UF (nome, sigla) VALUES ('Pará', 'PA');
INSERT INTO UF (nome, sigla) VALUES ('Paraíba', 'PB');
INSERT INTO UF (nome, sigla) VALUES ('Paraná', 'PR');
INSERT INTO UF (nome, sigla) VALUES ('Pernambuco', 'PE');
INSERT INTO UF (nome, sigla) VALUES ('Piauí', 'PI');
INSERT INTO UF (nome, sigla) VALUES ('Rio de Janeiro', 'RJ');
INSERT INTO UF (nome, sigla) VALUES ('Rio Grande do Norte', 'RN');
INSERT INTO UF (nome, sigla) VALUES ('Rio Grande do Sul', 'RS');
INSERT INTO UF (nome, sigla) VALUES ('Rondônia', 'RO');
INSERT INTO UF (nome, sigla) VALUES ('Roraima', 'RR');
INSERT INTO UF (nome, sigla) VALUES ('Santa Catarina', 'SC');
INSERT INTO UF (nome, sigla) VALUES ('São Paulo', 'SP');
INSERT INTO UF (nome, sigla) VALUES ('Sergipe', 'SE');
INSERT INTO UF (nome, sigla) VALUES ('Tocantins', 'TO');

INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (1, 'São Paulo', 25, 12345678L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (2, 'Rio de Janeiro', 25, 6789123L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (3, 'Salvador', 25, 345678L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (4, 'Brasília', 25, 4567890L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (5, 'Fortaleza', 25, 1234567L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (6, 'Belo Horizonte', 25, 5678901L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (7, 'Manaus', 4, 2345678L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (8, 'Curitiba', 16, 8901234L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (9, 'Recife', 17, 6789012L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (10, 'Porto Alegre', 20, 7890123L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (11, 'Goiânia', 9, 5678901L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (12, 'Belém', 14, 456789L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (13, 'São Luís', 10, 345678L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (14, 'Maceió', 2, 234567L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (15, 'Natal', 20, 123456L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (16, 'Teresina', 18, 567890L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (17, 'João Pessoa', 15, 678901L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (18, 'Aracaju', 26, 2345678L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (19, 'Campo Grande', 11, 789012L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (20, 'Cuiabá', 12, 890123L);

INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (21, 'Goiânia', 9, 1000L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (22, 'Belém', 14, 4569L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (23, 'São Luís', 10, 5678L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (24, 'Maceió', 2, 2567L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (25, 'Natal', 20, 1456L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (26, 'Teresina', 18, 56890L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (27, 'João Pessoa', 15, 67801L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (28, 'Aracaju', 26, 0L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (29, 'Campo Grande', 11, 9012L);
INSERT INTO Municipio (id, nome, uf_id, populacao) VALUES (30, 'Cuiabá', 25, 890123L);


